function cromulon --description "Planet Music audition call"
	set_color yellow
	echo "        ___"
	echo "    . -^   `--,"
	echo "   /# =========`-_"
	echo "  /# (--====___====\\"
	echo " /#   .- --.  . --.|"
	echo "/##   |  * ) (   * ),"
	echo "|##   \    /\ \   / |  ┌─┐┬ ┬┌─┐┬ ┬  ┌┬┐┌─┐"
	echo "|###   ---   \ ---  |  └─┐├─┤│ ││││  │││├┤ "
	echo "|####      ___)    #|  └─┘┴ ┴└─┘└┴┘  ┴ ┴└─┘"
	echo  "|######           ##|  ┬ ┬┬ ┬┌─┐┌┬┐  ┬ ┬┌─┐┬ ┬  ┌─┐┌─┐┌┬┐"
	echo " \\##### ---------- /   │││├─┤├─┤ │   └┬┘│ ││ │  │ ┬│ │ │ "
	echo "  \\####           (    └┴┘┴ ┴┴ ┴ ┴    ┴ └─┘└─┘  └─┘└─┘ ┴ "
	echo "   `\\###          |"
	echo "     \\###         |"
	echo "      \\##        |"
	echo "       \\###.    .)"
	echo "        `======/"
	echo ""
	set_color normal
end
